---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-dockerfile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-dockerfile
  template:
    metadata:
      labels:
        app: second-dockerfile
    spec:
      containers:
        - name: second-dockerfile
          image: akin4dada/second-dockerfile:1.0
          ports:
          - containerPort:  80
...
